'use client';
import {type ReactNode} from 'react';
import {Select,SelectTrigger,SelectContent,SelectItem,SelectValue,SelectGroup,SelectLabel} from '@/components/ui/select';
import {Slider} from '@/components/ui/slider';
import {Switch} from '@/components/ui/switch';
import {Tooltip,TooltipContent,TooltipTrigger} from '@/components/ui/tooltip';
export function IconButton({children,label,onClick,active=false,disabled=false,className='',...rest}:{children:ReactNode;label:string;onClick?:()=>void;active?:boolean;disabled?:boolean;className?:string}&React.ButtonHTMLAttributes<HTMLButtonElement>){return <Tooltip><TooltipTrigger asChild><button type="button" className={`icon-button ${active?'active':''} ${className}`} aria-label={label} disabled={disabled} onClick={onClick} {...rest}>{children}</button></TooltipTrigger><TooltipContent>{label}</TooltipContent></Tooltip>;}
export function Choice({label,value,onChange,options,className=''}:{label:string;value:string;onChange:(s:string)=>void;options:(string|{label:string;value:string;disabled?:boolean})[];className?:string}){return <Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label} className={`choice ${className}`}><SelectValue /></SelectTrigger><SelectContent>{options.map(o=>typeof o==='string'?<SelectItem key={o} value={o}>{o}</SelectItem>:<SelectItem key={o.value} value={o.value} disabled={o.disabled}>{o.label}</SelectItem>)}</SelectContent></Select>;}
export function Range({label,value,onChange,min=0,max=1,step=.01,suffix='',format,onBegin,onEnd}:{label:string;value:number;onChange:(v:number)=>void;min?:number;max?:number;step?:number;suffix?:string;format?:(v:number)=>string;onBegin?:()=>void;onEnd?:()=>void}){return <label className="range-field"><span>{label}<output>{format?format(value):Number(value.toFixed(2))}{suffix}</output></span><Slider aria-label={label} value={[value]} min={min} max={max} step={step} onPointerDown={onBegin} onValueChange={v=>onChange(v[0])} onValueCommit={onEnd}/></label>;}
export function Toggle({label,checked,onChange}:{label:string;checked:boolean;onChange:(v:boolean)=>void}){return <label className="toggle-field"><span>{label}</span><Switch checked={checked} onCheckedChange={onChange} aria-label={label}/></label>;}
export function NumberField({label,value,onChange,step=1,min,max,suffix}:{label:string;value:number;onChange:(v:number)=>void;step?:number;min?:number;max?:number;suffix?:string}){return <label className="number-field"><span>{label}</span><div><input aria-label={label} type="number" value={Number(value.toFixed(3))} step={step} min={min} max={max} onChange={e=>{const n=e.currentTarget.valueAsNumber;if(Number.isFinite(n))onChange(Math.min(max??Infinity,Math.max(min??-Infinity,n)));}}/>{suffix&&<small>{suffix}</small>}</div></label>;}
export function ColorField({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <label className="color-field"><span>{label}</span><div><input aria-label={label} type="color" value={value} onChange={e=>onChange(e.target.value)}/><span>{value.toUpperCase()}</span></div></label>;}
export function Section({title,children,open=false}:{title:string;children:ReactNode;open?:boolean}){return <details className="inspector-section" open={open}><summary>{title}<span>+</span></summary><div className="section-content">{children}</div></details>;}
export function FontPicker({value,onChange,fonts}:{value:string;onChange:(v:string)=>void;fonts:{name:string;family:string}[]}){return <Select value={value} onValueChange={onChange}><SelectTrigger className="choice" aria-label="Font family"><SelectValue/></SelectTrigger><SelectContent>{fonts.length>0&&<SelectGroup><SelectLabel>Project Fonts</SelectLabel>{fonts.map(f=><SelectItem value={f.family} key={f.family}><span style={{fontFamily:`"${f.family}"`}}>{f.name}</span></SelectItem>)}</SelectGroup>}<SelectGroup><SelectLabel>Studio fonts</SelectLabel>{['Arial','Arial Black','Impact','Georgia','Verdana','Trebuchet MS','Courier New','monospace','serif'].map(f=><SelectItem key={f} value={f}><span style={{fontFamily:f}}>{f}</span></SelectItem>)}</SelectGroup></SelectContent></Select>;}
