'use client';
import {useEffect,useState} from 'react';
import {Upload,Music2,Image as ImageIcon,Film,Plus,Type,AudioLines,Check,Shuffle,Bookmark,Palette,Download,Trash2,FolderOpen,Sparkles,Layers} from 'lucide-react';
import {toast} from 'sonner';
import {store,useEditor} from '@/lib/lyricforge/store';
import {assets} from '@/lib/lyricforge/assets';
import {audioEngine} from '@/lib/lyricforge/audio';
import {PRESETS,applyPreset,type Preset} from '@/lib/lyricforge/presets';
import {saveSetting,loadSetting,download} from '@/lib/lyricforge/project-manager';
import {makeTrack,makeClip,formatTime,uid,type Asset,type Clip} from '@/lib/lyricforge/model';
import {ColorField,Range,Choice,Toggle,Section} from './Controls';
export function addMedia(a:Asset){if(a.type==='font')return;const p=store.project;const tr=makeTrack(a.type,a.type==='audio'?'Song':a.type==='video'?'Background video':'Background image');const c=makeClip(a.type,tr.id,a.type==='audio'?0:audioEngine.time(),a.type==='audio'?a.duration!:p.duration,a.name);c.assetId=a.id;c.style={x:.5,y:.5};if(a.type==='audio')c.loop=false;store.update(x=>({...x,tracks:[...x.tracks,tr],clips:[...x.clips,c],duration:Math.max(x.duration,c.end)}));store.select([c.id]);}
export function MediaPanel({onImport}:{onImport:()=>void}){const {project}=useEditor();return <div className="library-section"><div className="panel-heading"><h2>Media</h2><span className="count-badge">{project.assets.length}</span></div><div className="panel-scroll"><button className="media-drop" onClick={onImport}><Upload size={24}/><strong>Drop your files here</strong><span>or browse your device</span></button><p className="hint media-hint">Audio, images, video, lyrics & fonts.<br/>Your media stays on this device.</p>{project.assets.filter(a=>a.type!=='font').map(a=><div className="media-card" key={a.id}><button className="media-thumb" onClick={()=>addMedia(a)} aria-label={`Add ${a.name} to timeline`}>{a.type==='image'?<img src={assets.urls.get(a.id)} alt={a.name}/>:a.type==='video'?<Film size={24}/>:<Music2 size={24}/>}<span><Plus size={16}/></span></button><div><strong title={a.name}>{a.name}</strong><small>{a.type.toUpperCase()} · {a.duration?formatTime(a.duration):Math.round(a.size/1024)+' KB'}</small></div><button title="Remove unused asset" aria-label={`Remove ${a.name}`} onClick={()=>{if(project.clips.some(c=>c.assetId===a.id)){toast('Remove its clips from the timeline first.');return;}store.update(p=>({...p,assets:p.assets.filter(x=>x.id!==a.id)}));}}><Trash2 size={13}/></button></div>)}<h4 className="library-subheading">Project fonts</h4>{project.assets.filter(a=>a.type==='font').map(a=><div className="font-card" key={a.id} style={{fontFamily:`"${a.fontFamily}"`}}><span>Aa</span>{a.name}</div>)}<button className="soft-button full" onClick={onImport}><Plus size={14}/>Import a font</button></div></div>;}
export function PresetPanel(){const {project}=useEditor();const [custom,setCustom]=useState<Preset[]>([]);const [name,setName]=useState('');useEffect(()=>{void loadSetting<Preset[]>('presets').then(p=>setCustom(p||[]));},[]);const apply=(preset:Preset)=>{store.update(p=>applyPreset(p,preset));toast(`${preset.name} style applied`);};return <div className="library-section"><div className="panel-heading"><h2>Presets</h2><button className="icon-button" title="Random preset" aria-label="Random preset" onClick={()=>apply(PRESETS[Math.floor(Math.random()*PRESETS.length)])}><Shuffle size={17}/></button></div><p className="panel-description">Find your sound. Make it your own.</p><div className="panel-scroll"><div className="preset-grid">{[...custom,...PRESETS].map((preset,i)=><button key={preset.name+i} className={`preset-card ${project.preset===preset.name?'chosen':''}`} onClick={()=>apply(preset)} title={preset.mood}><div className="preset-art" style={{background:`linear-gradient(135deg,${preset.colors[0]},${preset.colors[1]})`,color:preset.colors[2],fontFamily:preset.font}}><span style={{textTransform:preset.style.uppercase?'uppercase':undefined}}>Aa</span><div className="preset-bars">{[1,2,3,4,5,6,7].map(n=><i key={n} style={{height:5+(n%3)*4}}/>)}</div>{project.preset===preset.name&&<Check size={14}/>}</div><span className="preset-name">{preset.name}</span></button>)}</div><div className="save-preset"><h4><Bookmark size={15}/>Save your own style</h4><input aria-label="Custom preset name" placeholder="Give your style a name" value={name} onChange={e=>setName(e.target.value)}/><button className="soft-button full" disabled={!name.trim()} onClick={()=>{const preset:Preset={name:name.trim(),mood:'Your custom style',colors:[project.background.color,project.background.color2,project.lyricStyle.accent],font:project.lyricStyle.font,style:{...project.lyricStyle},visualizer:project.clips.find(c=>c.kind==='visualizer')?.visualizer||'None'};const next=[preset,...custom.filter(p=>p.name!==preset.name)];setCustom(next);void saveSetting('presets',next);setName('');toast('Custom preset saved');}}>Save preset</button><button className="text-button" onClick={()=>download(new Blob([JSON.stringify({name:project.preset,style:project.lyricStyle,background:project.background},null,2)],{type:'application/json'}),'lyricforge-style.json')}><Download size={13}/>Export style settings</button></div></div></div>;}
export function TextPanel(){const add=(text:string,size:number,y:number,entrance:Clip['style']['entrance'])=>{const c=store.add('text',audioEngine.time(),text);store.patch(c.id,{style:{size,y,entrance,karaoke:'Off'}});};return <div className="library-section"><div className="panel-heading"><h2>Text</h2><Type size={18}/></div><div className="panel-scroll"><button className="text-template large" onClick={()=>add('YOUR SONG TITLE',76,.25,'Rise')}>Add a title<span>Make an entrance</span></button><button className="text-template" onClick={()=>add('Artist name',42,.33,'Fade')}>Artist name<span>The person behind the music</span></button><button className="text-template small" onClick={()=>add('Written & performed by you',30,.8,'Fade')}>Add credits<span>A little recognition</span></button><button className="text-template watermark" onClick={()=>add('@yourname',24,.93,'None')}>@yourname<span>Add a watermark</span></button><button className="soft-button full" onClick={()=>add('Your text',48,.5,'Fade')}><Plus size={14}/>Custom text layer</button><div className="hint-box">Drag text directly in the preview. Use the inspector for precise typography and motion.</div></div></div>;}
export function EffectsPanel(){const {project}=useEditor();const b=project.background;const patch=(partial:Partial<typeof b>)=>store.update(p=>({...p,background:{...p.background,...partial}}),'background');return <div className="library-section"><div className="panel-heading"><h2>Background & effects</h2></div><div className="panel-scroll"><Section title="Background" open><Choice label="Background type" value={b.type} onChange={type=>patch({type:type as typeof b.type})} options={[{label:'Gradient',value:'gradient'},{label:'Solid color',value:'solid'},{label:'Animated pattern',value:'pattern'}]}/><ColorField label="Color" value={b.color} onChange={color=>patch({color})}/>{b.type!=='solid'&&<><ColorField label="Second color" value={b.color2} onChange={color2=>patch({color2})}/><Range label="Angle" value={b.angle} max={360} step={1} suffix="°" onChange={angle=>patch({angle})}/><Range label="Motion" value={b.motion} onChange={motion=>patch({motion})}/></>}<Range label="Vignette" value={b.vignette} onChange={vignette=>patch({vignette})}/></Section><h4 className="library-subheading">Reactive overlays</h4>{['Particles','Glow','Beat flash'].map(mode=><button className="element-option" key={mode} onClick={()=>{const c=store.add('visualizer',0);store.patch(c.id,{visualizer:mode as Clip['visualizer'],name:mode,style:{y:.5,scale:1,opacity:.65}});}}><Sparkles size={18}/><span>{mode}</span><Plus size={16}/></button>)}<p className="hint">Effects respond to the imported song. Their intensity and color remain editable.</p></div></div>;}
export function ElementsPanel(){return <div className="library-section"><div className="panel-heading"><h2>Elements</h2><AudioLines size={18}/></div><p className="panel-description">Let the music move the picture.</p><div className="panel-scroll">{(['Bars','Spectrum','Waveform','Circle','Particles','Glow','Beat flash'] as const).map((mode,i)=><button className="visualizer-card" key={mode} onClick={()=>{const c=store.add('visualizer',0);store.patch(c.id,{visualizer:mode,name:mode});}}><div className={'visualizer-symbol symbol-'+i}>{mode==='Circle'?<span className="circle-symbol"/>:<AudioLines size={60} strokeWidth={.8}/>}</div><div><strong>{mode}</strong><Plus size={17}/></div></button>)}</div></div>;}
