'use client';
import {uid,type Asset} from './model';
import {audioEngine} from './audio';
export class AssetManager {
 blobs=new Map<string,Blob>();urls=new Map<string,string>();visuals=new Map<string,HTMLImageElement|HTMLVideoElement>();fonts=new Map<string,FontFace>();
 async load(a:Asset,blob:Blob){if(this.urls.has(a.id))return;this.blobs.set(a.id,blob);const url=URL.createObjectURL(blob);this.urls.set(a.id,url);try{if(a.type==='audio')await audioEngine.decode(blob,a.id);else if(a.type==='font'){const face=new FontFace(a.fontFamily!,await blob.arrayBuffer());await face.load();document.fonts.add(face);this.fonts.set(a.id,face);}else if(a.type==='image'){const img=new Image();img.src=url;await img.decode();this.visuals.set(a.id,img);}else{const v=document.createElement('video');v.src=url;v.preload='auto';v.muted=true;v.playsInline=true;await new Promise<void>((resolve,reject)=>{const timer=setTimeout(()=>fail(),20000);const cleanup=()=>{clearTimeout(timer);v.onloadeddata=null;v.onerror=null;};const fail=()=>{cleanup();reject(new Error(`This browser cannot decode ${a.name}. Convert it to H.264 MP4 or WebM.`));};v.onloadeddata=()=>{cleanup();resolve();};v.onerror=fail;});a.duration=v.duration*1000;this.visuals.set(a.id,v);}}catch(e){this.remove(a.id);throw e;}}
 async import(file:File):Promise<Asset>{const ext=file.name.split('.').pop()?.toLowerCase()||'';let type:Asset['type'];if(['ttf','otf','woff','woff2'].includes(ext))type='font';else if(file.type.startsWith('audio/')||['mp3','wav','flac','aac','m4a','ogg'].includes(ext))type='audio';else if(file.type.startsWith('image/')||['png','jpg','jpeg','webp','gif'].includes(ext))type='image';else if(file.type.startsWith('video/')||['mp4','webm','mov'].includes(ext))type='video';else throw new Error(`Unsupported media: ${file.name}`);const a:Asset={id:uid(),name:file.name,type,mime:file.type||({png:'image/png',jpg:'image/jpeg',jpeg:'image/jpeg',webp:'image/webp',gif:'image/gif',mp4:'video/mp4',webm:'video/webm',mov:'video/quicktime',wav:'audio/wav',mp3:'audio/mpeg',flac:'audio/flac',ogg:'audio/ogg',m4a:'audio/mp4',aac:'audio/aac',ttf:'font/ttf',otf:'font/otf',woff:'font/woff',woff2:'font/woff2'} as Record<string,string>)[ext]||'application/octet-stream',size:file.size};if(type==='font')a.fontFamily=file.name.replace(/\.[^.]+$/,'').replace(/[^\p{L}\p{N}\s_-]/gu,'')+' '+a.id.slice(0,5);await this.load(a,file);if(type==='audio')a.duration=audioEngine.buffers.get(a.id)!.duration*1000;return a;}
 remove(id:string){const url=this.urls.get(id);if(url)URL.revokeObjectURL(url);this.urls.delete(id);this.blobs.delete(id);const media=this.visuals.get(id);if(media instanceof HTMLVideoElement){media.pause();media.removeAttribute('src');media.load();}this.visuals.delete(id);const font=this.fonts.get(id);if(font)document.fonts.delete(font);this.fonts.delete(id);audioEngine.buffers.delete(id);}
}
export const assets=new AssetManager();
