'use client';
import {useSyncExternalStore} from 'react';
import {clamp,type Project,type Clip} from './model';
export class AudioEngine {
 context:AudioContext|null=null;master:GainNode|null=null;analyser:AnalyserNode|null=null;buffers=new Map<string,AudioBuffer>();sources:AudioBufferSourceNode[]=[];project:Project|null=null;playing=false;position=0;speed=1;volume=.8;loop:[number,number]|null=null;private anchor=0;private anchorPosition=0;private raf=0;listeners=new Set<()=>void>();private lastEmit=0;private snapshot={time:0,playing:false,speed:1,volume:.8};
 ensure(){if(!this.context){this.context=new AudioContext();this.master=this.context.createGain();this.master.gain.value=this.volume;this.analyser=this.context.createAnalyser();this.analyser.fftSize=1024;this.master.connect(this.analyser);this.analyser.connect(this.context.destination);}return this.context;}
 subscribe=(f:()=>void)=>{this.listeners.add(f);return()=>{this.listeners.delete(f);};};getSnapshot=()=>this.snapshot;
 emit(){this.snapshot={time:this.position,playing:this.playing,speed:this.speed,volume:this.volume};this.listeners.forEach(f=>f());}
 time(){if(!this.playing||!this.context)return this.position;return Math.min(this.project?.duration??Infinity,this.anchorPosition+Math.max(0,this.context.currentTime-this.anchor)*1000*this.speed);}
 setProject(p:Project){const old=this.project;this.project=p;if(this.playing&&old&&JSON.stringify(old.clips.filter(c=>c.kind==='audio'))+JSON.stringify(old.tracks)!==JSON.stringify(p.clips.filter(c=>c.kind==='audio'))+JSON.stringify(p.tracks)){const t=this.time();this.pause();this.position=t;void this.play();}}
 stopSources(){for(const s of this.sources){try{s.stop();s.disconnect();}catch{}}this.sources=[];}
 async play(){if(this.playing)return;const ctx=this.ensure();await ctx.resume();if(this.position>=(this.project?.duration||0))this.position=0;this.anchor=ctx.currentTime+.025;this.anchorPosition=this.position;this.playing=true;this.schedule();this.emit();this.tick();}
 schedule(){const ctx=this.ensure();const p=this.project;if(!p)return;const solo=p.tracks.some(t=>t.kind==='audio'&&t.solo);for(const c of p.clips.filter(c=>c.kind==='audio')){const tr=p.tracks.find(t=>t.id===c.trackId);if(!tr||tr.mute||!tr.visible||solo&&!tr.solo||c.end<=this.position)continue;const buffer=this.buffers.get(c.assetId||'');if(!buffer)continue;const source=ctx.createBufferSource();source.buffer=buffer;source.playbackRate.value=this.speed;const start=Math.max(this.position,c.start);const off=(c.offset+start-c.start)/1000;if(off>=buffer.duration&&!c.loop)continue;source.loop=c.loop;source.connect(this.master!);source.start(this.anchor+(start-this.position)/1000/this.speed,off%buffer.duration,(c.end-start)/1000);this.sources.push(source);}}
 tick=()=>{if(!this.playing)return;this.position=this.time();if(this.loop&&this.position>=this.loop[1]){this.seek(this.loop[0]);return;}if(this.position>=(this.project?.duration||0)){this.pause();return;}if(performance.now()-this.lastEmit>35){this.emit();this.lastEmit=performance.now();}this.raf=requestAnimationFrame(this.tick);};
 pause(){if(this.playing)this.position=this.time();this.playing=false;cancelAnimationFrame(this.raf);this.stopSources();this.emit();}
 toggle(){return this.playing?this.pause():this.play();}
 seek(t:number){const was=this.playing;this.pause();this.position=clamp(t,0,this.project?.duration||Infinity);this.emit();if(was)void this.play();}
 stop(){this.pause();this.seek(0);}
 rate(speed:number){const was=this.playing;this.pause();this.speed=speed;this.emit();if(was)void this.play();}
 setVolume(volume:number){this.volume=volume;if(this.master)this.master.gain.value=volume;this.emit();}
 async decode(blob:Blob,id:string){const buffer=await this.ensure().decodeAudioData(await blob.arrayBuffer());this.buffers.set(id,buffer);return buffer;}
 async mono16k(buffer:AudioBuffer){const ctx=new OfflineAudioContext(1,Math.ceil(buffer.duration*16000),16000);const s=ctx.createBufferSource();s.buffer=buffer;s.connect(ctx.destination);s.start();return (await ctx.startRendering()).getChannelData(0);}
 async mix(p:Project){const sampleRate=48000;const ctx=new OfflineAudioContext(2,Math.max(1,Math.ceil(p.duration/1000*sampleRate)),sampleRate);const solo=p.tracks.some(t=>t.kind==='audio'&&t.solo);let has=false;for(const c of p.clips.filter(c=>c.kind==='audio')){const tr=p.tracks.find(t=>t.id===c.trackId);const buffer=this.buffers.get(c.assetId||'');if(!tr||tr.mute||!tr.visible||solo&&!tr.solo||!buffer||c.start>=p.duration||(!c.loop&&c.offset/1000>=buffer.duration))continue;has=true;const source=ctx.createBufferSource();source.buffer=buffer;source.loop=c.loop;source.connect(ctx.destination);source.start(c.start/1000,c.offset/1000%buffer.duration,Math.min(c.end,p.duration)/1000-c.start/1000);}return has?await ctx.startRendering():null;}
}
export const audioEngine=new AudioEngine();
export function useTransport(){return useSyncExternalStore(audioEngine.subscribe,audioEngine.getSnapshot,audioEngine.getSnapshot);}
export function bufferToWav(b:AudioBuffer){const n=b.numberOfChannels,length=b.length*n*2;const ab=new ArrayBuffer(44+length);const v=new DataView(ab);const write=(o:number,s:string)=>{for(let i=0;i<s.length;i++)v.setUint8(o+i,s.charCodeAt(i));};write(0,'RIFF');v.setUint32(4,36+length,true);write(8,'WAVEfmt ');v.setUint32(16,16,true);v.setUint16(20,1,true);v.setUint16(22,n,true);v.setUint32(24,b.sampleRate,true);v.setUint32(28,b.sampleRate*n*2,true);v.setUint16(32,n*2,true);v.setUint16(34,16,true);write(36,'data');v.setUint32(40,length,true);const data=Array.from({length:n},(_,i)=>b.getChannelData(i));for(let i=0;i<b.length;i++)for(let c=0;c<n;c++)v.setInt16(44+(i*n+c)*2,clamp(data[c][i],-1,1)*32767,true);return new Blob([ab],{type:'audio/wav'});}
export function makeDemoAudio(){const ctx=audioEngine.ensure();const sr=22050;const b=ctx.createBuffer(1,24*sr,sr);const d=b.getChannelData(0);const roots=[130.81,103.83,155.56,116.54];for(let i=0;i<d.length;i++){const t=i/sr;const root=roots[Math.floor(t/6)%4];const beat=t%.5;const chord=[1,1.25,1.5,2].reduce((a,k)=>a+Math.sin(t*Math.PI*2*root*k)*.025*(.7+.3*Math.sin(t*2)),0);const kick=Math.sin(2*Math.PI*(45*beat+9*(1-Math.exp(-beat*25))))*Math.exp(-beat*22)*.18;const arp=Math.sin(t*Math.PI*2*root*[2,2.5,3,4][Math.floor(t*4)%4])*Math.exp(-(t%.25)*12)*.05;d[i]=(chord+kick+arp)*Math.min(t,1,24-t);}return b;}
