'use client';
import {type Project} from './model';
import {audioEngine} from './audio';
import {Renderer} from './renderer';
export type ExportCodec='avc'|'vp9'|'av1';
export interface ExportSettings {codec:ExportCodec;width:number;height:number;fps:24|30|60;bitrate:number;audioBitrate:number;}
export async function availableCodecs(width=1920,height=1080){if(typeof VideoEncoder==='undefined')return {avc:typeof WebAssembly!=='undefined',vp9:false,av1:false};const {canEncodeVideo}=await import('mediabunny');const caps=Object.fromEntries(await Promise.all((['avc','vp9','av1'] as const).map(async c=>[c,await canEncodeVideo(c,{width,height})]))) as Record<ExportCodec,boolean>;caps.avc||=typeof WebAssembly!=='undefined';return caps;}
export async function renderVideo(project:Project,settings:ExportSettings,onProgress:(progress:number,status:string)=>void,signal:AbortSignal){
 const {Output,Mp4OutputFormat,WebMOutputFormat,BufferTarget,CanvasSource,AudioBufferSource,canEncodeVideo,canEncodeAudio,Quality}=await import('mediabunny');
 if(!await canEncodeVideo(settings.codec,{width:settings.width,height:settings.height})){if(settings.codec==='avc'){const {renderSoftwareMp4}=await import('./software-exporter');return renderSoftwareMp4(project,settings,onProgress,signal);}throw new Error(`${settings.codec.toUpperCase()} encoding is unavailable in this browser. Choose MP4 instead.`);}
 const isMp4=settings.codec==='avc';if(isMp4&&!await canEncodeAudio('aac')){const {registerAacEncoder}=await import('@mediabunny/aac-encoder');registerAacEncoder();}
 const canvas=document.createElement('canvas');canvas.width=settings.width;canvas.height=settings.height;const renderer=new Renderer();const p={...project,width:settings.width,height:settings.height,fps:settings.fps};const output=new Output({format:isMp4?new Mp4OutputFormat({fastStart:'in-memory'}):new WebMOutputFormat(),target:new BufferTarget()});const video=new CanvasSource(canvas,{codec:settings.codec,quality:new Quality({bitrate:settings.bitrate}),keyFrameInterval:2});output.addVideoTrack(video,{frameRate:settings.fps});
 try {onProgress(0,'Preparing fonts and mixing audio…');await document.fonts.ready;const mixed=await audioEngine.mix(project);let sound:InstanceType<typeof AudioBufferSource>|null=null;if(mixed){sound=new AudioBufferSource({codec:isMp4?'aac':'opus',quality:new Quality({bitrate:settings.audioBitrate})});output.addAudioTrack(sound);}await output.start();if(signal.aborted)throw new DOMException('Export cancelled','AbortError');if(sound&&mixed){await sound.add(mixed);sound.close();}
 const frames=Math.ceil(project.duration/1000*settings.fps);for(let i=0;i<frames;i++){if(signal.aborted)throw new DOMException('Export cancelled','AbortError');const time=i/settings.fps*1000;await renderer.prepareMedia(p,time);renderer.draw(canvas,p,time,{export:true});await video.add(i/settings.fps,Math.min(1/settings.fps,project.duration/1000-i/settings.fps));if(i%6===0){onProgress(i/frames*98,`Rendering frame ${i+1} of ${frames}`);await new Promise(resolve=>setTimeout(resolve,0));}}video.close();onProgress(99,'Finalizing video and audio…');await output.finalize();onProgress(100,'Your video is ready');return new Blob([output.target.buffer!],{type:isMp4?'video/mp4':'video/webm'});
 }catch(e){if(output.state!=='finalized'&&output.state!=='canceled')await output.cancel();throw e;}finally{renderer.dispose();canvas.width=0;canvas.height=0;}
}
