'use client';
import {assets} from './assets';
import {VideoPool} from './video-pool';
import {effectiveStyle,clamp,type Project,type Clip,type Style,evenlyTimeWords} from './model';
import {animationState,keyedStyle,ease} from './animation';
import type {AnimationRenderState} from './animation-runtime';
import type {EffectInstance,TransitionInstance} from './creative-assets';
import {resolveCreativeFrame,type CreativeClipFrame,type CreativeFramePlan,type CreativeTransitionFrame} from './creative-runtime';
import type {CreativeQuality} from './creative-registry';
import type {CreativeDiagnostic,ResolvedEffect} from './effect-runtime';
import {renderEffect} from './render-effects';
import {renderTransition} from './render-transitions';
import {RenderSurfacePool} from './render-surfaces';
import {echoSamples,posterizeSampleTime} from './temporal-effects';
export interface RenderOptions { guides?:boolean; selected?:string[]; export?:boolean; quality?:CreativeQuality; }
export interface Bounds {id:string;x:number;y:number;width:number;height:number;}
function signature(value:EffectInstance|TransitionInstance){return JSON.stringify(value);}
export class Renderer {
 bounds:Bounds[]=[];
 creativeDiagnostics:CreativeDiagnostic[]=[];
 private videos=new VideoPool();private lastProject:Project|null=null;private surfaces=new RenderSurfacePool();
 private signatures=new Map<string,string>();private quarantine=new Set<string>();private diagnosticDedupe=new Set<string>();
 dispose(){this.videos.dispose();this.surfaces.dispose();}

 private quality(options:RenderOptions){return options.export?'export':options.quality??'preview-high';}
 recordFrame(p:Project,time:number,options:RenderOptions={}){const plan=resolveCreativeFrame(p,time,this.quality(options));return {plan,operations:[...plan.operationOrder,...(options.export?[]:['editor:overlay'])]};}
 private syncSignatures(p:Project){
  const current=new Map<string,string>();for(const c of p.clips)for(const effect of c.effects??[])if(effect.enabled)current.set(effect.id,signature(effect));for(const effect of p.masterEffects??[])if(effect.enabled)current.set(effect.id,signature(effect));for(const transition of p.transitions??[])current.set(transition.id,signature(transition));
  const ids=new Set([...this.signatures.keys(),...current.keys()]);for(const id of ids)if(this.signatures.get(id)!==current.get(id)){this.quarantine.delete(id);this.diagnosticDedupe.delete(id);this.creativeDiagnostics=this.creativeDiagnostics.filter(d=>d.instanceId!==id);}this.signatures=current;
 }
 private runtimeFailure(instanceId:string,assetId:string,error:unknown){this.quarantine.add(instanceId);if(this.diagnosticDedupe.has(instanceId))return;this.diagnosticDedupe.add(instanceId);this.creativeDiagnostics.push({kind:'runtime',instanceId,assetId,message:error instanceof Error?error.message:String(error)});}
 private effectNumber(effect:ResolvedEffect,key:string,fallback=0){const value=effect.params[key];return typeof value==='number'&&Number.isFinite(value)?value:fallback;}
 private applyEffectStack(rawStack:readonly EffectInstance[],resolvedAt:(sampleTime:number)=>readonly ResolvedEffect[],baseAt:(sampleTime:number,recordBounds:boolean)=>CanvasImageSource,p:Project,time:number,key:string,quality:CreativeQuality,endExclusive=rawStack.length,recordBounds=true):CanvasImageSource{
  let current=baseAt(time,recordBounds);const resolvedById=new Map(resolvedAt(time).map(effect=>[effect.instanceId,effect]));const limit=Math.min(endExclusive,rawStack.length);const frameIndex=Math.max(0,Math.round(time/1000*p.fps));
  for(let i=0;i<limit;i++){
   const raw=rawStack[i];if(!raw.enabled)continue;const effect=resolvedById.get(raw.id);if(!effect||this.quarantine.has(effect.instanceId))continue;
   try{
    if(effect.runtime==='effect.posterize-time'){
     const sampleTime=posterizeSampleTime(time,this.effectNumber(effect,'fps',12));
     current=this.applyEffectStack(rawStack,resolvedAt,baseAt,p,sampleTime,`${key}:posterize:${i}:${Math.round(sampleTime*1000)}`,quality,i,false);continue;
    }
    if(effect.runtime==='effect.echo'){
     const target=this.surfaces.acquire(p.width,p.height,1,`${key}:echo:${i}:${effect.instanceId}:${Math.round(time*1000)}`);const samples=echoSamples(time,this.effectNumber(effect,'delayMs',120),this.effectNumber(effect,'trails',4),this.effectNumber(effect,'decay',.6),quality);
     for(const sample of [...samples].reverse()){
      const historical=this.applyEffectStack(rawStack,resolvedAt,baseAt,p,sample.timeMs,`${key}:echo:${i}:sample:${Math.round(sample.timeMs*1000)}`,quality,i,false);target.ctx.save();target.ctx.globalAlpha=sample.alpha;target.ctx.drawImage(historical,0,0,p.width,p.height);target.ctx.restore();
     }
     target.ctx.drawImage(current,0,0,p.width,p.height);current=target.canvas;continue;
    }
    const target=this.surfaces.acquire(p.width,p.height,1,`${key}:fx:${i}:${effect.instanceId}:${Math.round(time*1000)}`);renderEffect(target.ctx,current,effect,{width:p.width,height:p.height,frameIndex,timeMs:time,quality,pool:this.surfaces});current=target.canvas;
   }catch(error){this.runtimeFailure(effect.instanceId,effect.assetId,error);}
  }
  return current;
 }
 private drawClip(ctx:CanvasRenderingContext2D,p:Project,frame:CreativeClipFrame,exporting:boolean){const c=frame.clip,t=frame.sampleTimeMs;if(c.kind==='lyrics'||c.kind==='text')this.text(ctx,p,c,t,false,frame.animation.state);else if(c.kind==='image'||c.kind==='video')this.media(ctx,p,c,t,exporting);else if(c.kind==='visualizer')this.visualizer(ctx,p,c,t);else if(c.kind==='effect')this.effect(ctx,p,c,t);}
 private clipFrameAt(p:Project,clipId:string,time:number,quality:CreativeQuality){const plan=resolveCreativeFrame(p,time,quality);return plan.clips.find(frame=>frame.clip.id===clipId)??plan.transitions.flatMap(transition=>[transition.outgoing,transition.incoming]).find(frame=>frame.clip.id===clipId);}
 private renderClipEffects(p:Project,clipId:string,time:number,options:RenderOptions,key:string,currentFrame?:CreativeClipFrame){
  const clip=p.clips.find(item=>item.id===clipId);if(!clip)return null;const rawStack=clip.effects??[];const quality=this.quality(options);const frameCache=new Map<number,CreativeClipFrame|undefined>();if(currentFrame)frameCache.set(time,currentFrame);const frameAt=(sampleTime:number)=>{if(!frameCache.has(sampleTime))frameCache.set(sampleTime,this.clipFrameAt(p,clipId,sampleTime,quality));return frameCache.get(sampleTime);};
  const baseAt=(sampleTime:number,recordBounds:boolean)=>{const surface=this.surfaces.acquire(p.width,p.height,1,`${key}:source:${Math.round(sampleTime*1000)}`);const before=this.bounds.length;const frame=frameAt(sampleTime);if(frame)this.drawClip(surface.ctx as unknown as CanvasRenderingContext2D,p,frame,!!options.export);if(!recordBounds)this.bounds.length=before;return surface.canvas;};
  const resolvedAt=(sampleTime:number)=>frameAt(sampleTime)?.effects.effects??[];
  return this.applyEffectStack(rawStack,resolvedAt,baseAt,p,time,key,quality);
 }
 private drawCreativeClip(ctx:CanvasRenderingContext2D,p:Project,frame:CreativeClipFrame,time:number,options:RenderOptions,key:string){const raw=p.clips.find(item=>item.id===frame.clip.id)?.effects??[];if(!raw.some(effect=>effect.enabled)){this.drawClip(ctx,p,frame,!!options.export);return;}const output=this.renderClipEffects(p,frame.clip.id,time,options,key,frame);if(output)ctx.drawImage(output,0,0,p.width,p.height);else this.drawClip(ctx,p,frame,!!options.export);}
 private drawTransitionFrame(ctx:CanvasRenderingContext2D,p:Project,frame:CreativeTransitionFrame,time:number,options:RenderOptions){
  const outgoing=this.renderClipEffects(p,frame.outgoing.clip.id,time,options,`transition:${frame.instance.id}:out`,frame.outgoing)??this.surfaces.acquire(p.width,p.height,1,`transition:${frame.instance.id}:out:fallback`).canvas;
  const incoming=this.renderClipEffects(p,frame.incoming.clip.id,time,options,`transition:${frame.instance.id}:in`,frame.incoming)??this.surfaces.acquire(p.width,p.height,1,`transition:${frame.instance.id}:in:fallback`).canvas;
  const resolution=frame.resolution;if(this.quarantine.has(frame.instance.id)||!resolution.runtime||!resolution.quality){ctx.drawImage(time<resolution.window!.cutMs?outgoing:incoming,0,0,p.width,p.height);return;}
  const target=this.surfaces.acquire(p.width,p.height,1,`transition:${frame.instance.id}:mix`);try{renderTransition(target.ctx,outgoing,incoming,{instanceId:frame.instance.id,runtime:resolution.runtime,params:resolution.params,progress:resolution.progress,quality:resolution.quality},{width:p.width,height:p.height,frameIndex:Math.max(0,Math.round(time/1000*p.fps)),timeMs:time});ctx.drawImage(target.canvas,0,0,p.width,p.height);}catch(error){this.runtimeFailure(frame.instance.id,frame.instance.assetId,error);ctx.drawImage(time<resolution.window!.cutMs?outgoing:incoming,0,0,p.width,p.height);}
 }
 private renderScene(ctx:CanvasRenderingContext2D,p:Project,time:number,options:RenderOptions,plan:CreativeFramePlan){
  this.background(ctx,p,time);const normalById=new Map(plan.clips.map(frame=>[frame.clip.id,frame]));const transitionsByTrack=new Map<string,CreativeTransitionFrame[]>();for(const transition of plan.transitions){const list=transitionsByTrack.get(transition.outgoing.clip.trackId)??[];list.push(transition);transitionsByTrack.set(transition.outgoing.clip.trackId,list);}
  for(const track of [...p.tracks].reverse()){if(!track.visible||track.kind==='audio')continue;ctx.save();ctx.globalAlpha=track.opacity;const activeNominal=p.clips.filter(c=>c.trackId===track.id&&c.start<=time&&c.end>time);for(const c of activeNominal){const frame=normalById.get(c.id);if(!frame)continue;this.drawCreativeClip(ctx,p,frame,time,options,`clip:${c.id}`);}for(const transition of transitionsByTrack.get(track.id)??[])this.drawTransitionFrame(ctx,p,transition,time,options);if(track.kind==='lyrics'&&p.lyricStyle.neighbors&&activeNominal.length){const all=p.clips.filter(c=>c.trackId===track.id).sort((a,b)=>a.start-b.start);const idx=all.findIndex(c=>c.id===activeNominal[0].id);for(const [offset,color] of [[-1,p.lyricStyle.previousColor],[1,p.lyricStyle.upcomingColor]] as const){const n=all[idx+offset];if(n&&!activeNominal.some(a=>a.id===n.id)){const sty=effectiveStyle(p,activeNominal[0]);this.text(ctx,p,{...n,style:{...n.style,y:sty.y+offset*.115,color,size:sty.size*.55,opacity:.5,entrance:'None',idle:'None',exit:'None',karaoke:'Off'}},clamp(time,n.start+500,n.end-500),true);}}}ctx.restore();}
 }
 private renderMasterEffects(p:Project,time:number,options:RenderOptions,currentPlan:CreativeFramePlan){
  const rawStack=p.masterEffects??[];const quality=this.quality(options);const plans=new Map<number,CreativeFramePlan>([[time,currentPlan]]);const planAt=(sampleTime:number)=>{let plan=plans.get(sampleTime);if(!plan){plan=resolveCreativeFrame(p,sampleTime,quality);plans.set(sampleTime,plan);}return plan;};
  const baseAt=(sampleTime:number,recordBounds:boolean)=>{const surface=this.surfaces.acquire(p.width,p.height,1,`master:scene:${Math.round(sampleTime*1000)}`);const before=this.bounds.length;this.renderScene(surface.ctx as unknown as CanvasRenderingContext2D,p,sampleTime,{...options,guides:false,selected:[]},planAt(sampleTime));if(!recordBounds)this.bounds.length=before;return surface.canvas;};
  const resolvedAt=(sampleTime:number)=>planAt(sampleTime).masterEffects.effects;
  return this.applyEffectStack(rawStack,resolvedAt,baseAt,p,time,'master',quality);
 }
 draw(canvas:HTMLCanvasElement|OffscreenCanvas,p:Project,time:number,options:RenderOptions={}){
  if(this.lastProject!==p){this.videos.prune(new Set(p.clips.filter(c=>c.kind==='video').map(c=>c.id)));this.lastProject=p;}this.syncSignatures(p);const quality=this.quality(options);const plan=resolveCreativeFrame(p,time,quality);this.creativeDiagnostics=[...plan.diagnostics,...this.creativeDiagnostics.filter(d=>d.kind==='runtime')];const ctx=canvas.getContext('2d') as CanvasRenderingContext2D;if(!ctx)return;const W=canvas.width,H=canvas.height;ctx.save();ctx.clearRect(0,0,W,H);ctx.scale(W/p.width,H/p.height);this.bounds=[];
  if((p.masterEffects??[]).some(effect=>effect.enabled)){const output=this.renderMasterEffects(p,time,options,plan);ctx.drawImage(output,0,0,p.width,p.height);}else this.renderScene(ctx,p,time,options,plan);
  if(options.guides&&!options.export){ctx.save();ctx.strokeStyle='#ffffff45';ctx.lineWidth=p.width/W;ctx.setLineDash([7,7]);ctx.strokeRect(p.width*.05,p.height*.05,p.width*.9,p.height*.9);ctx.restore();}
  if(options.selected?.length&&!options.export){ctx.save();ctx.strokeStyle='#f2b66d';ctx.lineWidth=1.5*p.width/W;for(const b of this.bounds.filter(b=>options.selected!.includes(b.id))){ctx.strokeRect(b.x,b.y,b.width,b.height);for(const [x,y] of [[b.x,b.y],[b.x+b.width,b.y],[b.x,b.y+b.height],[b.x+b.width,b.y+b.height]]){ctx.fillStyle='#f2b66d';ctx.fillRect(x-3*p.width/W,y-3*p.width/W,6*p.width/W,6*p.width/W);}}ctx.restore();}
  ctx.restore();
 }
 background(ctx:CanvasRenderingContext2D,p:Project,t:number){const {width:w,height:h,background:b}=p;if(b.type==='solid')ctx.fillStyle=b.color;else {const a=b.angle*Math.PI/180;const drift=Math.sin(t/13000)*b.motion*.2;const g=ctx.createLinearGradient(w*(.5-Math.cos(a)*.6+drift),h*(.5-Math.sin(a)*.6),w*(.5+Math.cos(a)*.6),h*(.5+Math.sin(a)*.6));g.addColorStop(0,b.color);g.addColorStop(1,b.color2);ctx.fillStyle=g;}ctx.fillRect(0,0,w,h);if(b.type==='pattern'){ctx.save();ctx.strokeStyle=p.lyricStyle.accent+'22';ctx.lineWidth=1;for(let i=0;i<32;i++){const y=i*h/25+(t/90)%(h/25);ctx.beginPath();ctx.moveTo(0,y);ctx.bezierCurveTo(w*.3,y+Math.sin(t/3000+i)*h*.2,w*.7,y-h*.1,w,y);ctx.stroke();}ctx.restore();}if(b.vignette){const g=ctx.createRadialGradient(w*.5,h*.45,h*.05,w*.5,h*.5,Math.max(w,h)*.7);g.addColorStop(0,'#00000000');g.addColorStop(1,`rgba(0,0,0,${b.vignette})`);ctx.fillStyle=g;ctx.fillRect(0,0,w,h);}}
 text(ctx:CanvasRenderingContext2D,p:Project,c:Clip,t:number,neighbor=false,creative?:AnimationRenderState){
  const s=keyedStyle(effectiveStyle(p,c),c,t);const u=p.height/1080;const duration=Math.max(10,s.animationDuration);const enter=ease((t-c.start-s.delay)/duration,s.easing);const exit=ease((c.end-t)/duration,s.easing);const en=animationState(s.entrance,enter,(t-c.start)/1000,s.intensity,s.direction);const ex=animationState(s.exit,exit,(c.end-t)/1000,s.intensity,-s.direction);const idle=animationState(s.idle,1,t/1000,s.intensity,s.direction,true);const state=creative??{x:en.x+ex.x+idle.x,y:en.y+ex.y+idle.y,scaleX:en.scaleX*ex.scaleX*idle.scaleX,scaleY:en.scaleY*ex.scaleY*idle.scaleY,rotation:en.rotation+ex.rotation+idle.rotation,alpha:en.alpha*ex.alpha*idle.alpha,blur:en.blur+ex.blur,reveal:Math.min(en.reveal,ex.reveal),tracking:0,colorShift:0,glow:0};const words=c.words.length?c.words:evenlyTimeWords(c.text,c.start,c.end);let visible=s.uppercase?c.text.toUpperCase():c.text;
  const reveal=state.reveal;if(s.entrance==='Word Reveal'||s.exit==='Word Reveal')visible=visible.split(/\s+/).slice(0,Math.ceil(visible.split(/\s+/).length*reveal)).join(' ');else if(reveal<1)visible=visible.slice(0,Math.ceil(visible.length*reveal));
  ctx.save();ctx.globalCompositeOperation=c.blend;ctx.globalAlpha*=s.opacity*state.alpha;ctx.translate(s.x*p.width+state.x*u,s.y*p.height+state.y*u);ctx.rotate(s.rotation*Math.PI/180+state.rotation);ctx.scale(s.scale*state.scaleX,s.scale*state.scaleY);
  ctx.font=`${s.italic?'italic ':''}${s.weight} ${s.size*u}px "${s.font}", sans-serif`;ctx.textBaseline='middle';ctx.textAlign='left';ctx.letterSpacing=`${(s.letterSpacing+state.tracking)*u}px`;ctx.lineJoin='round';ctx.lineWidth=s.stroke*u;ctx.strokeStyle=s.strokeColor;ctx.shadowColor=(s.glow||state.glow)?s.accent:'#000000b0';ctx.shadowBlur=(s.glow||s.shadow+state.glow)*u;ctx.shadowOffsetY=(s.glow||state.glow)?0:3*u;ctx.filter=`blur(${Math.max(0,s.blur+state.blur)*u}px) hue-rotate(${state.colorShift}deg)`;
  const maxWidth=p.width*.88/Math.max(1,s.scale);const lines:{text:string;index:number;width:number}[][]=[[]];let lineWidth=0;let wi=0;const gap=(ctx.measureText(' ').width+s.wordSpacing*u);for(const para of visible.split('\n')){if(wi>0){lines.push([]);lineWidth=0;}for(const word of para.split(/\s+/).filter(Boolean)){const width=ctx.measureText(word).width;if(lineWidth+width>maxWidth&&lines.at(-1)!.length){lines.push([]);lineWidth=0;}lines.at(-1)!.push({text:word,index:wi++,width});lineWidth+=width+gap;}}
  const widths=lines.map(line=>line.reduce((n,w)=>n+w.width+gap,0)-gap);const h=lines.length*s.size*u*s.lineHeight;const widest=Math.max(0,...widths);const boxX=s.align==='left'?0:s.align==='right'?-widest:-widest/2;
  if(s.boxOpacity){ctx.save();ctx.shadowBlur=0;ctx.fillStyle=s.boxColor;ctx.globalAlpha*=s.boxOpacity;ctx.beginPath();ctx.roundRect(boxX-s.padding*u,-h/2-s.padding*u,widest+s.padding*u*2,h+s.padding*u*2,s.radius*u);ctx.fill();ctx.restore();}
  const base=s.sectionColors?(c.section==='Chorus'?s.chorusColor:s.verseColor):s.color;
  for(let li=0;li<lines.length;li++){const line=lines[li];let x=s.align==='left'?0:s.align==='right'?-widths[li]:-widths[li]/2;const y=(li-(lines.length-1)/2)*s.size*u*s.lineHeight;
   for(const word of line){const timing=words[word.index];const progress=timing?clamp((t-timing.start)/Math.max(1,timing.end-timing.start),0,1):0;const current=!!timing&&t>=timing.start&&t<timing.end;const sung=timing&&t>=timing.start;ctx.save();ctx.translate(x+word.width/2,y);const react=current&&(s.karaoke==='Scale'||s.karaoke==='Bounce');if(react){const scale=s.karaoke==='Scale'?1.12:1+Math.sin(progress*Math.PI)*.12;ctx.scale(scale,scale);if(s.karaoke==='Bounce')ctx.translate(0,-Math.sin(progress*Math.PI)*12*u);}if(timing?.emphasized){ctx.shadowBlur=(s.glow+18)*u;}if(current&&s.emphasis!=='None'){const a=animationState(s.emphasis,1,t/1000,s.intensity,s.direction,true);ctx.translate(a.x*u,a.y*u);ctx.rotate(a.rotation);ctx.scale(a.scaleX,a.scaleY);ctx.globalAlpha*=a.alpha;}
   ctx.fillStyle=s.karaoke!=='Off'&&s.karaoke!=='Fill'&&sung||timing?.emphasized?s.accent:base;if(s.gradient){const g=ctx.createLinearGradient(0,-s.size*u/2,0,s.size*u/2);g.addColorStop(0,String(ctx.fillStyle));g.addColorStop(1,s.gradientColor);ctx.fillStyle=g;}if(s.stroke)ctx.strokeText(word.text,-word.width/2,0);ctx.fillText(word.text,-word.width/2,0);if(s.karaoke==='Fill'&&progress>0){ctx.save();ctx.beginPath();ctx.rect(-word.width/2-s.stroke*u,-s.size*u,word.width*progress+s.stroke*u,s.size*u*2);ctx.clip();ctx.fillStyle=s.accent;ctx.fillText(word.text,-word.width/2,0);ctx.restore();}if(s.underline){ctx.fillRect(-word.width/2,s.size*u*.5,word.width,Math.max(1,s.size*u*.04));}ctx.restore();x+=word.width+gap;}
  }
  ctx.restore();if(!neighbor)this.bounds.push({id:c.id,x:s.x*p.width+(boxX-s.padding*u)*s.scale,y:s.y*p.height-(h/2+s.padding*u)*s.scale,width:(widest+s.padding*u*2)*s.scale,height:(h+s.padding*u*2)*s.scale});
 }
 media(ctx:CanvasRenderingContext2D,p:Project,c:Clip,t:number,exporting:boolean){const media=c.kind==='video'?this.videos.get(c)?.video:assets.visuals.get(c.assetId||'');if(!media)return;const s=keyedStyle(effectiveStyle(p,c),c,t);if(media instanceof HTMLVideoElement){const pos=this.mediaTime(c,t,media.duration);if(!exporting&&Math.abs(media.currentTime-pos)>.065&&!media.seeking)media.currentTime=pos;if(media.readyState<2)return;}const width=media instanceof HTMLVideoElement?media.videoWidth:media.naturalWidth;const height=media instanceof HTMLVideoElement?media.videoHeight:media.naturalHeight;const factor=c.fit==='cover'?Math.max(p.width/width,p.height/height):Math.min(p.width/width,p.height/height);ctx.save();ctx.globalAlpha*=s.opacity;ctx.globalCompositeOperation=c.blend;ctx.translate(s.x*p.width,s.y*p.height);ctx.rotate(s.rotation*Math.PI/180);ctx.scale(s.scale,s.scale);ctx.filter=`blur(${s.blur*p.height/1080}px) brightness(${c.brightness}) contrast(${c.contrast}) saturate(${c.saturation}) hue-rotate(${c.hue}deg)`;ctx.drawImage(media,-width*factor/2,-height*factor/2,width*factor,height*factor);ctx.restore();this.bounds.push({id:c.id,x:s.x*p.width-width*factor*s.scale/2,y:s.y*p.height-height*factor*s.scale/2,width:width*factor*s.scale,height:height*factor*s.scale});}
 mediaTime(c:Clip,t:number,duration:number){const pos=(c.offset+t-c.start)/1000;return c.loop?pos/Math.max(duration,.001)>=0?pos%Math.max(duration,.001):0:clamp(pos,0,Math.max(0,duration-.001));}
 async prepareMedia(p:Project,t:number){const times=new Map<string,number>();for(const c of p.clips.filter(c=>c.kind==='video'&&c.start<=t&&c.end>t&&p.tracks.find(tr=>tr.id===c.trackId)?.visible))times.set(c.id,t);const plan=resolveCreativeFrame(p,t,'export');for(const transition of plan.transitions){if(transition.outgoing.clip.kind==='video')times.set(transition.outgoing.clip.id,transition.outgoing.sampleTimeMs);if(transition.incoming.clip.kind==='video')times.set(transition.incoming.clip.id,transition.incoming.sampleTimeMs);}for(const [id,sampleTime] of times){const c=p.clips.find(clip=>clip.id===id)!;const entry=this.videos.get(c);if(!entry)throw new Error('A background video is missing. Reimport its media.');await entry.ready;const v=entry.video;const target=this.mediaTime(c,sampleTime,v.duration);if(Math.abs(v.currentTime-target)<.0005&&v.readyState>=2)continue;await new Promise<void>((resolve,reject)=>{let timer:ReturnType<typeof setTimeout>;const cleanup=()=>{clearTimeout(timer);v.removeEventListener('seeked',done);v.removeEventListener('error',fail);};const done=()=>{cleanup();resolve();};const fail=()=>{cleanup();reject(new Error('Could not decode a background video frame.'));};v.addEventListener('seeked',done);v.addEventListener('error',fail);timer=setTimeout(fail,15000);v.currentTime=target;});}}
 energy(p:Project,t:number,c:Clip){let total=0,n=0;const radius=Math.round(c.smoothing*8);const at=Math.floor(t/20);for(let i=-radius;i<=0;i++){total+=p.energy[clamp(at+i,0,p.energy.length-1)]||0;n++;}return clamp(total/Math.max(1,n)*8*c.sensitivity,0,1);}
 visualizer(ctx:CanvasRenderingContext2D,p:Project,c:Clip,t:number){const s=keyedStyle(effectiveStyle(p,c),c,t);const energy=this.energy(p,t,c);const w=p.width*.7*s.scale,h=p.height*.14*s.scale;ctx.save();ctx.globalCompositeOperation=c.blend;ctx.translate(s.x*p.width,s.y*p.height);ctx.rotate(s.rotation*Math.PI/180);ctx.globalAlpha*=s.opacity;ctx.strokeStyle=s.accent;ctx.fillStyle=s.accent;ctx.lineWidth=Math.max(1,p.height/540);ctx.shadowBlur=s.glow;ctx.shadowColor=s.accent;const mode=c.visualizer||'Bars';if(mode==='Glow'||mode==='Beat flash'){const r=p.height*.4;const g=ctx.createRadialGradient(0,0,0,0,0,r);g.addColorStop(0,s.accent+Math.round(energy*160).toString(16).padStart(2,'0'));g.addColorStop(1,s.accent+'00');ctx.fillStyle=g;ctx.fillRect(-r,-r,r*2,r*2);}else if(mode==='Circle'){for(let i=0;i<64;i++){const a=i/64*Math.PI*2;const amp=this.band(p,t,i,c)*h;ctx.beginPath();ctx.moveTo(Math.cos(a)*h,Math.sin(a)*h);ctx.lineTo(Math.cos(a)*(h+amp),Math.sin(a)*(h+amp));ctx.stroke();}}else if(mode==='Particles'){for(let i=0;i<80;i++){const x=(Math.sin(i*79.17)*.5+.5)*w-w/2;const y=((i*53.7-t*.013*(1+energy))%(h*3)+h*3)%(h*3)-h*1.5;ctx.globalAlpha=s.opacity*(.15+energy*.7);ctx.beginPath();ctx.arc(x,y,1.5+(i%3),0,Math.PI*2);ctx.fill();}}else if(mode==='Waveform'){ctx.beginPath();for(let i=0;i<240;i++){const idx=Math.floor((t/p.duration+i/240*.02)*p.waveform.length)%Math.max(1,p.waveform.length);const amplitude=(p.waveform[idx]||0)*c.sensitivity;const y=Math.sin(i*.6+t*.003)*amplitude*h;const x=-w/2+i/239*w;i?ctx.lineTo(x,y):ctx.moveTo(x,y);}ctx.stroke();}else{for(let i=0;i<64;i++){const amp=this.band(p,t,i,c)*h;ctx.fillRect(-w/2+i*w/64,-Math.max(2,amp)/2,w/64*.46,Math.max(2,amp));}}ctx.restore();this.bounds.push({id:c.id,x:s.x*p.width-w/2,y:s.y*p.height-h,width:w,height:h*2});}
 band(p:Project,t:number,i:number,c:Clip){const frame=Math.floor(t/40);const bin=Math.min(31,Math.floor(i/2));const n=Math.max(1,Math.round(c.smoothing*6));let sum=0;for(let j=0;j<n;j++)sum+=p.spectrum?.[Math.max(0,frame-j)]?.[bin]||0;return clamp(sum/n*c.sensitivity,0,1);}
 effect(ctx:CanvasRenderingContext2D,p:Project,c:Clip,t:number){const s=keyedStyle(effectiveStyle(p,c),c,t);ctx.save();ctx.globalAlpha*=s.opacity;ctx.globalCompositeOperation=c.blend;ctx.fillStyle=s.color;ctx.globalAlpha*=this.energy(p,t,c)*s.intensity;ctx.fillRect(0,0,p.width,p.height);ctx.restore();}
}