'use client';
import {FFmpeg} from '@ffmpeg/ffmpeg';
import {Renderer} from './renderer';
import {audioEngine,bufferToWav} from './audio';
import type {Project} from './model';
import type {ExportSettings} from './exporter';
export async function renderSoftwareMp4(project:Project,settings:ExportSettings,onProgress:(p:number,s:string)=>void,signal:AbortSignal){
 const ffmpeg=new FFmpeg();const canvas=document.createElement('canvas');canvas.width=settings.width;canvas.height=settings.height;const renderer=new Renderer();const p={...project,width:settings.width,height:settings.height};let wasmUrl='';let lastError='';ffmpeg.on('log',({message})=>{if(/error|failed|invalid/i.test(message))lastError=message;});const check=()=>{if(signal.aborted)throw new DOMException('Export cancelled','AbortError');};const abort=()=>ffmpeg.terminate();signal.addEventListener('abort',abort,{once:true});
 try{check();onProgress(0,'Loading the local H.264 renderer…');const manifest=await fetch('/workers/ffmpeg-manifest.json',{signal}).then(r=>{if(!r.ok)throw new Error('The software renderer could not be downloaded.');return r.json();}) as {parts:string[]};const buffers:BlobPart[]=[];for(let i=0;i<manifest.parts.length;i++){const r=await fetch('/workers/'+manifest.parts[i],{signal});if(!r.ok)throw new Error('The software renderer download was interrupted.');buffers.push(await r.arrayBuffer());onProgress((i+1)/manifest.parts.length*3,'Loading the local H.264 renderer…');}wasmUrl=URL.createObjectURL(new Blob(buffers,{type:'application/wasm'}));await ffmpeg.load({classWorkerURL:location.origin+'/workers/ffmpeg-worker.js',coreURL:location.origin+'/workers/ffmpeg-core.js',wasmURL:wasmUrl});check();await document.fonts.ready;const mixed=await audioEngine.mix(project);check();if(mixed)await ffmpeg.writeFile('mix.wav',new Uint8Array(await bufferToWav(mixed).arrayBuffer()));const frames=Math.ceil(project.duration/1000*settings.fps);const chunkSize=settings.fps;const chunks:string[]=[];for(let start=0;start<frames;start+=chunkSize){check();const count=Math.min(chunkSize,frames-start);for(let j=0;j<count;j++){check();const time=(start+j)/settings.fps*1000;await renderer.prepareMedia(p,time);renderer.draw(canvas,p,time,{export:true});const png=await new Promise<Blob>((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(new Error('Could not render a frame.')),'image/png'));await ffmpeg.writeFile(`frame${String(j).padStart(4,'0')}.png`,new Uint8Array(await png.arrayBuffer()));if(j%6===0)onProgress(3+(start+j)/frames*88,`Rendering frame ${start+j+1} of ${frames}`);}const file=`segment-${Math.floor(start/chunkSize)}.ts`;onProgress(3+(start+count*.65)/frames*88,`Encoding ${Math.round((start+count)/settings.fps)} / ${Math.ceil(project.duration/1000)} seconds`);const status=await ffmpeg.exec(['-framerate',String(settings.fps),'-start_number','0','-i','frame%04d.png','-frames:v',String(count),'-c:v','libx264','-preset','ultrafast','-pix_fmt','yuv420p','-b:v',String(settings.bitrate),'-maxrate',String(settings.bitrate*1.5),'-bufsize',String(settings.bitrate*2),'-bf','0','-g',String(settings.fps*2),'-an','-f','mpegts',file]);if(status!==0)throw new Error('H.264 encoding failed. '+lastError);chunks.push(`file '${file}'\nduration ${count/settings.fps}`);for(let j=0;j<count;j++)await ffmpeg.deleteFile(`frame${String(j).padStart(4,'0')}.png`);}
 check();onProgress(93,'Combining video frames with the audio mix…');await ffmpeg.writeFile('segments.txt',new TextEncoder().encode(chunks.join('\n')));const args=['-f','concat','-safe','0','-i','segments.txt'];if(mixed)args.push('-i','mix.wav','-map','0:v:0','-map','1:a:0');args.push('-c:v','copy');if(mixed)args.push('-c:a','aac','-b:a',String(settings.audioBitrate));args.push('-t',String(project.duration/1000),'-movflags','+faststart','output.mp4');if(await ffmpeg.exec(args)!==0)throw new Error('Video finalization failed. '+lastError);check();const data=await ffmpeg.readFile('output.mp4') as Uint8Array;onProgress(100,'Your MP4 is ready');return new Blob([data as BlobPart],{type:'video/mp4'});
 }catch(e){if(signal.aborted)throw new DOMException('Export cancelled','AbortError');throw e;}finally{renderer.dispose();signal.removeEventListener('abort',abort);ffmpeg.terminate();if(wasmUrl)URL.revokeObjectURL(wasmUrl);canvas.width=0;canvas.height=0;}
}
