'use client';
import {makeClip,uid,type Clip,type Word} from './model';
import {publicPath} from './public-path';
export interface TranscriptionUpdate {status:string;progress:number;words?:Word[];}
export interface TranscriptionProvider { id:string;label:string;local:boolean;transcribe(audio:Float32Array,onProgress:(u:TranscriptionUpdate)=>void,signal:AbortSignal):Promise<Word[]>; }
export class LocalWhisper implements TranscriptionProvider {
 id='local-whisper';label='Whisper · on this device';local=true;
 constructor(public model='Xenova/whisper-tiny.en'){}
 transcribe(audio:Float32Array,onProgress:(u:TranscriptionUpdate)=>void,signal:AbortSignal){return new Promise<Word[]>((resolve,reject)=>{if(signal.aborted){reject(new DOMException('Transcription cancelled','AbortError'));return;}const worker=new Worker(publicPath('/workers/transcription.js'),{type:'module'});const abort=()=>{worker.terminate();reject(new DOMException('Transcription cancelled','AbortError'));};signal.addEventListener('abort',abort,{once:true});worker.onerror=e=>{worker.terminate();signal.removeEventListener('abort',abort);reject(new Error(e.message||'The local model could not start.'));};worker.onmessage=({data})=>{if(data.type==='done'||data.type==='error'){worker.terminate();signal.removeEventListener('abort',abort);data.type==='done'?resolve(data.words):reject(new Error(data.error));}else onProgress(data);};worker.postMessage({audio,model:this.model},[audio.buffer]);});}
}
export class HttpTranscription implements TranscriptionProvider {
 id='http';label='Custom transcription endpoint';local=false;
 constructor(public endpoint:string,public audioFile:Blob,public filename:string){}
 async transcribe(_audio:Float32Array,onProgress:(u:TranscriptionUpdate)=>void,signal:AbortSignal){const url=new URL(this.endpoint);if(url.protocol!=='https:'&&!['localhost','127.0.0.1'].includes(url.hostname))throw new Error('Use an HTTPS transcription endpoint.');onProgress({status:'Uploading audio to '+url.host,progress:5});const form=new FormData();form.append('file',this.audioFile,this.filename);form.append('response_format','verbose_json');form.append('timestamp_granularities[]','word');const res=await fetch(url,{method:'POST',body:form,signal,credentials:'omit'});if(!res.ok)throw new Error(`Transcription endpoint returned ${res.status}.`);const data=await res.json() as {words?:unknown};if(!Array.isArray(data.words)||data.words.length>200000)throw new Error('The endpoint must return { words: [{ word, start, end, confidence? }] } with timestamps in seconds.');const words:Word[]=(data.words as {word?:string;text?:string;start:number;end:number;confidence?:number}[]).map((w:{word?:string;text?:string;start:number;end:number;confidence?:number})=>({text:String(w.word??w.text??''),start:Math.round(w.start*1000),end:Math.round(w.end*1000),...(typeof w.confidence==='number'?{confidence:w.confidence}:{})}));if(words.some(w=>!Number.isFinite(w.start)||!Number.isFinite(w.end)||w.start<0||w.end<w.start||w.end>86400000||w.text.length>500||w.confidence!==undefined&&(!Number.isFinite(w.confidence)||w.confidence<0||w.confidence>1)))throw new Error('Invalid timestamps returned by the provider.');return words.filter(w=>w.text.trim()).sort((a,b)=>a.start-b.start);}
}
export function wordsToClips(words:Word[],trackId:string):Clip[]{const groups:Word[][]=[];let current:Word[]=[];for(const w of words){if(current.length&&(w.start-current.at(-1)!.end>800||current.length>=8||/[.!?]$/.test(current.at(-1)!.text))){groups.push(current);current=[];}current.push(w);}if(current.length)groups.push(current);return groups.map(ws=>{const text=ws.map(w=>w.text.trim()).join(' ');const confidence=ws.every(w=>typeof w.confidence==='number')?ws.reduce((v,w)=>v+w.confidence!,0)/ws.length:undefined;return {...makeClip('lyrics',trackId,ws[0].start,Math.max(ws.at(-1)!.end,ws[0].start+100),text),words:ws,confidence,timingSource:'detected'};});}
